# Generated by Django 3.2 on 2021-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='address', max_length=100, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='2001-01-01', verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=30, null=True, verbose_name='father name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='last name', max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default='1', verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='last name', max_length=30, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.TimeField(max_length=10, unique=True, verbose_name='phone'),
        ),
    ]
