# Generated by Django 3.2 on 2021-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210423_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Александровна'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Мария', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Иванова', max_length=30, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(max_length=10, unique=True, verbose_name='0931234567'),
        ),
    ]
